version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - "db:database"

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wagtail
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pswdpass

#  frontend:
#    build:
#      context: .
#      dockerfile: ./compose/local/frontend/Dockerfile
#    image: wagtail_bootstrap_blog_frontend
#    command: npm start
#    volumes:
#      - .:/app
#      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
#      - /app/frontend/node_modules

volumes:
  postgres_data:
