# Generated by Django 3.2.5 on 2021-07-28 04:03

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210726_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Страница блогов'},
        ),
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': 'Страница с формой'},
        ),
        migrations.AlterModelOptions(
            name='postpage',
            options={'verbose_name': 'Страница постов'},
        ),
        migrations.AddField(
            model_name='postpage',
            name='is_close_comment',
            field=models.BooleanField(default=True, verbose_name='Отключать комменарии автоматически'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='Платная'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='is_picture',
            field=models.BooleanField(default=False, verbose_name='Отключить главную картинку'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='is_recl',
            field=models.BooleanField(default=False, verbose_name='Рекламная'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='is_yandex',
            field=models.BooleanField(default=True, verbose_name='Выводится в Яндекс.новостях'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField([('h1', wagtail.core.blocks.CharBlock()), ('h2', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(label='Параграф')), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code')), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Внешний контент')), ('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Изображения')), ('image_carousel', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображения'), label='Карусель')), ('thumbnail_gallery', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображения'), label='Миниатюры'))], blank=True, verbose_name='Контент на странице'),
        ),
    ]
