# Generated by Django 3.2.5 on 2021-07-29 02:42

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210728_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(help_text='Отображаемая имформация при поике', max_length=120, verbose_name='Метка')),
            ],
        ),
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField([('h1', wagtail.core.blocks.CharBlock()), ('h2', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(label='Параграф')), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code')), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Внешний контент')), ('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Изображения')), ('image_carousel', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображения'), label='Карусель')), ('thumbnail_gallery', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображения'), label='Миниатюры')), ('quote', wagtail.core.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, verbose_name='Контент на странице'),
        ),
    ]
