# Generated by Django 3.2.5 on 2021-08-01 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customimage_customrendition'),
        ('blog', '0009_auto_20210729_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='search_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Search image'),
        ),
    ]
