# Generated by Django 3.2.5 on 2021-08-01 08:04

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_postpage_search_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='tables',
            field=wagtail.core.fields.StreamField([('Table', wagtail.contrib.table_block.blocks.TableBlock())], default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tables',
            name='lable',
            field=models.CharField(help_text='Отображаемая имформация при поиске', max_length=120, verbose_name='Метка'),
        ),
    ]
