# Generated by Django 3.2.5 on 2021-08-04 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0005_customimage_customrendition'),
        ('blog', '0014_auto_20210804_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('post_date', models.DateTimeField(default=datetime.datetime.today, help_text='Время отображаемое на сайте', verbose_name='Время создания')),
                ('body', wagtail.core.fields.StreamField([('h1', wagtail.core.blocks.CharBlock()), ('h2', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock(label='Параграф')), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code')), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(label='Внешний контент')), ('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Изображения')), ('image_carousel', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображения'), label='Карусель')), ('thumbnail_gallery', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(label='Изображения'), label='Миниатюры')), ('quote', wagtail.core.blocks.BlockQuoteBlock(label='Цитата'))], blank=True, verbose_name='Контент на странице')),
                ('is_recl_0', models.BooleanField(default=False, verbose_name='Не выводится в Яндекс.новостях')),
                ('is_recl_1', models.BooleanField(default=False, verbose_name='Не выводить на главной')),
                ('is_recl_2', models.BooleanField(default=False, verbose_name='Не выводить в индексе')),
                ('is_recl_3', models.BooleanField(default=False, verbose_name='Не дублировать')),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.customimage', verbose_name='Изображения в заголовке')),
            ],
            options={
                'verbose_name': 'Запись',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='is_recl_0',
            field=models.BooleanField(default=False, verbose_name='Не выводится в Яндекс.новостях'),
        ),
        migrations.CreateModel(
            name='PostPage3Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to='blog.blogarticlepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_postpage3tag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogarticlepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.PostPage3Tag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
