# Generated by Django 3.2.5 on 2021-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_annotate'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotate',
            name='id_messege',
            field=models.CharField(max_length=120),
        ),
    ]
